"""Calibrate continuous strokes with the unchanged upstream GPU shaders.

Optional development tool: pip install moderngl numpy
The generated TypeScript data is checked in; no Python is needed to run the app.
"""
import hashlib
import json
import re
from pathlib import Path

import moderngl
import numpy as np

root = Path(__file__).resolve().parents[1]
ctx = moderngl.create_standalone_context(backend='egl', require=330)
vertex = '''#version 330
in vec2 position;
out vec2 coord;
void main(){coord=position*.5+.5;gl_Position=vec4(position,0,1);}
'''
sources = {}
passes = {}
for name in ['WaterRipple', 'WaveSimulation']:
    source = (root / 'src/shaders' / (name + '.frag')).read_text()
    sources[name] = hashlib.sha256(source.encode()).hexdigest()
    fragment = re.sub(r'precision\s+\w+\s+\w+\s*;', '', source)
    fragment = fragment.replace('varying vec2 coord;', 'in vec2 coord;')
    fragment = fragment.replace('texture2D(', 'texture(').replace('gl_FragColor', 'outputColor')
    program = ctx.program(vertex_shader=vertex,
                          fragment_shader='#version 330\nout vec4 outputColor;\n' + fragment)
    vertices = ctx.buffer(np.array([-1,-1,1,-1,-1,1,1,1], dtype='f4').tobytes())
    quad = ctx.vertex_array(program, [(vertices, '2f', 'position')])
    program['tInput'].value = 0
    program['poolWidth'].value = program['poolLength'].value = 1.
    if 'delta' in program: program['delta'].value = (1/256, 1/256)
    passes[name] = (program, quad)

textures = [ctx.texture((256,256), 4, dtype='f4') for _ in range(2)]
for texture in textures:
    texture.filter = (moderngl.NEAREST, moderngl.NEAREST)
    texture.repeat_x = texture.repeat_y = False
buffers = [ctx.framebuffer([texture]) for texture in textures]
ctx.viewport = (0,0,256,256)
current = 0

def step(name):
    global current
    textures[current].use(0)
    buffers[1-current].use()
    passes[name][1].render(moderngl.TRIANGLE_STRIP)
    current = 1-current

profiles = []
for radius in [.012,.016,.02,.025,.03,.038,.045,.055,.065]:
    for buffer in buffers: buffer.clear(0,0,0,0)
    current = 0
    program = passes['WaterRipple'][0]
    program['center'].value = (0.,0.)
    program['radius'].value = radius
    program['strength'].value = -.02
    step('WaterRipple')
    radii, amplitudes = [], []
    previous_radius, previous_amplitude = radius, .02
    for age in range(141):
        if age % 4 == 0:
            height = np.frombuffer(textures[current].read(), dtype='f4').reshape(256,256,4)[:,:,0]
            # Average the four cardinal directions. Track the outward depression,
            # excluding the central oscillation and all secondary wavelets.
            axis = (height[127:129,128:].mean(axis=0)
                    + height[127:129,:128].mean(axis=0)[::-1]
                    + height[128:,127:129].mean(axis=1)
                    + height[:128,127:129].mean(axis=1)[::-1]) / 4
            lower = max(0, int(previous_radius*128 - 2))
            upper = min(127, int(age*.7072 + radius*256 + 5))
            index = lower + int(np.argmin(axis[lower:upper+1]))
            offset = 0.
            if 0 < index < 127:
                a,b,c = map(float, axis[index-1:index+2])
                denominator = a-2*b+c
                if denominator > 1e-12: offset = float(np.clip(.5*(a-c)/denominator,-.5,.5))
            measured = (index+.5+offset)/128
            previous_radius = max(previous_radius, measured)
            previous_amplitude = min(previous_amplitude, max(1e-8, -float(axis[index])))
            radii.append(round(previous_radius,7))
            amplitudes.append(round(previous_amplitude/.02,7))
        if age < 140: step('WaveSimulation')
    profiles.append({'dropRadius':radius, 'radii':radii, 'amplitudes':amplitudes})

data = {'grid':256, 'sampleEvery':4, 'lastStep':140, 'damping':.995,
        'shaderHashes':sources, 'profiles':profiles}
output = root / 'src/WaveProfile.ts'
output.write_text('// Generated by scripts/generate-wave-profile.py using the upstream GPU shaders.\n'
                  + 'export const waveProfile = ' + json.dumps(data,separators=(',',':')) + ';\n')
print(json.dumps({'profiles':len(profiles), 'sourceShadersUnchanged':True, 'output':str(output)}))
